"use client"
import {useMemo,useState} from 'react'
import {geoNaturalEarth1,geoPath} from 'd3-geo'
import {feature} from 'topojson-client'
import world from 'world-atlas/countries-50m.json'
import type {MapAssignment} from '@/lib/types'
const W=1200,H=640;const wf=feature(world as never,(world as unknown as {objects:{countries:never}}).objects.countries) as unknown as {features:any[]};const projection=geoNaturalEarth1().fitExtent([[22,22],[W-22,H-22]],{type:'Sphere'});const path=geoPath(projection)
function parse(v:string){const[y,m,d]=v.split('-').map(Number);return new Date(Date.UTC(y,m-1,d))}function iso(d:Date){return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}-${String(d.getUTCDate()).padStart(2,'0')}`}function add(v:string,n:number){const d=parse(v);d.setUTCDate(d.getUTCDate()+n);return iso(d)}function active(i:MapAssignment,d:string){return d>=i.assignment_start&&d<=i.assignment_end}function ini(n:string){return n.split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase()}
export default function WorldMap({assignments,initialDate}:{assignments:MapAssignment[];initialDate:string}){const[selectedDate,setDate]=useState(initialDate);const[selected,setSelected]=useState<MapAssignment|null>(null);const items=useMemo(()=>assignments.filter(i=>active(i,selectedDate)),[assignments,selectedDate]);const days=Array.from({length:13},(_,i)=>add(selectedDate,i-6));return <section className="world-app"><header className="world-top"><div className="world-brand"><div className="world-logo">G</div><div><div className="world-eyebrow">Golfpassi</div><div className="world-title">Maailmalla</div></div></div><div className="world-date">{new Intl.DateTimeFormat('fi-FI',{weekday:'long',day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(parse(selectedDate))}</div></header><div className="map-shell"><svg className="world-svg" viewBox={`0 0 ${W} ${H}`}>{wf.features.map((c,i)=><path key={i} className="country" d={path(c as never)??undefined}/>)}{items.map((it,i)=>{const pt=projection([it.longitude,it.latitude]);if(!pt)return null;const x=pt[0]+i*28,y=pt[1]+i*15;return <g key={it.assignment_id} className="leader-marker" transform={`translate(${x},${y})`} tabIndex={0} onClick={()=>setSelected(it)}><circle className="avatar-halo" r="34"/><circle className="avatar-ring" r="27"/><circle className="avatar-fallback" r="24"/><text className="avatar-initials" y="1">{ini(it.leader_name)}</text><text className="leader-label" x="35" y="-2">{it.leader_name}</text><text className="place-label" x="35" y="14">{it.destination_name}</text></g>})}</svg><div className="live-pill"><span className="live-dot"/>{items.length} {items.length===1?'matkanvetäjä':'matkanvetäjää'} maailmalla</div>{selected?<article className="detail-card"><button className="detail-close" onClick={()=>setSelected(null)}>×</button><div className="detail-name">{selected.leader_name}</div><div className="detail-place">{selected.destination_name}, {selected.country}</div><div className="detail-trip">{selected.trip_name}</div><div className="detail-period">{selected.assignment_start} – {selected.assignment_end}</div></article>:null}{assignments.some(i=>i.is_demo)?<div className="demo-note">Esimerkkidata käytössä</div>:null}</div><div className="date-nav"><button className="nav-btn" onClick={()=>setDate(add(selectedDate,-7))}>←</button><div className="date-strip">{days.map(d=><button key={d} className={`day-btn ${assignments.some(i=>active(i,d))?'has':''} ${d===selectedDate?'active':''}`} onClick={()=>{setDate(d);setSelected(null)}}><div className="dow">{new Intl.DateTimeFormat('fi-FI',{weekday:'short',timeZone:'UTC'}).format(parse(d))}</div><div className="daynum">{parse(d).getUTCDate()}</div><div className="signal"/></button>)}</div><button className="nav-btn" onClick={()=>setDate(add(selectedDate,7))}>→</button></div><div className="world-caption">Klikkaa ihmistä. Ei raportteja – vain kuka on missä.</div></section>}
